spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bankxdb
    username: bankx
    password: bankx1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc.time_zone: Asia/Kolkata